language: generic
before_install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - brew install hello
  - ~/.linuxbrew/bin/brew install hello
  - exit 1
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk
script:
  - make
