language: generic
before_install:
  - |
    wget https://github.com/github/hub/releases/download/v2.2.5/hub-linux-amd64-2.2.5.tgz
    tar zvxvf hub-linux-amd64-2.2.5.tgz
    sudo ./hub-linux-amd64-2.2.5/install
  - hub version
  - hub release
  - exit 0
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y golang
  - git clone https://github.com/github/hub.git
  - cd hub
  - ./script/build
  - ./bin/hub release
  - exit 0
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - |
    test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
    test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
    test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile
    echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.profile
  - brew install --devel hub
  - hub release
  - exit 0
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk
script:
  - make
