language: generic
before_install:
  - |
    echo "Installing Go 1.8.5"
    export GOFILE=go1.8.5.linux-amd64.tar.gz
    wget -q https://redirector.gvt1.com/edgedl/go/${GOFILE}
    if [ "$GOROOT" ] ; then
      echo "Target directory $GOROOT"
      sudo rm -rf $GOROOT
      sudo mkdir -p $GOROOT
      sudo tar -C $GOROOT --strip-components=1 -xzf ${GOFILE}
    else
      echo "Target directory /usr/local/go"
      sudo tar -C /usr/local -xzf ${GOFILE}
      export PATH=$PATH:/usr/local/go/bin
    fi
    go version
  - |
    echo "Cloning latest hub source files"
    git clone https://github.com/github/hub.git
    echo "Building hub"
    ./hub/script/build
    export PATH=$PATH:$(pwd)/hub/bin
    echo $PATH
    hub version
  - exit 0
  - hub version
  - hub release
  - |
    {
      hub release delete pierrecamembert-patch-3-fromhub
    }
    echo "Trying to edit instead"
    hub release create -m "hello" -m "[ci skip]" -t pierrecamembert-patch-3 pierrecamembert-patch-3-fromhub
  - hub release
  - exit 0
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk
script:
  - make
