language: generic
script:
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk
  - make
  - |
    echo "Installing Go 1.8.5"
    export GOFILE=go1.8.5.linux-amd64.tar.gz
    wget -q https://redirector.gvt1.com/edgedl/go/${GOFILE}
    if [ "$GOROOT" ] ; then
      echo "Target directory $GOROOT"
      sudo rm -rf $GOROOT
      sudo mkdir -p $GOROOT
      sudo tar -C $GOROOT --strip-components=1 -xzf ${GOFILE}
    else
      echo "Target directory /usr/local/go"
      sudo tar -C /usr/local -xzf ${GOFILE}
      export PATH=$PATH:/usr/local/go/bin
    fi
    go version
  - |
    echo "Building GitHub CLI hub from latest source files"
    git clone https://github.com/github/hub.git
    cd hub
    ./script/build
    export PATH=$PATH:$(pwd)/bin
    cd ..
    hub version
  - |
    echo "Uploading release"
    echo "Generate tag name from SHA-1 hash because it should be different from branch name"
    export HASH=$(echo -n "${TRAVIS_BRANCH}" | sha1sum)
    export TAG=${TRAVIS_BRANCH}-tag-${HASH:0:40}
    {
      echo "Creating tag without triggering Travis CI (This is allowed to fail if the tag exists already)"
      git config --global user.email "deploy@travis-ci.org"
      git config --global user.name "Deployment Bot (from Travis CI)"
      git tag -a -m "This tag has been auto-generated by Travis CI build #${TRAVIS_BUILD_NUMBER}. [ci skip]" "${TAG}"
      git push "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" "${TAG}"
    }
    {
      echo "Trying to delete former release (This is allowed to fail if there is no former release)"
      hub release delete "${TAG}"
    }
    echo "Creating new release"
    hub release create --prerelease -m ${TRAVIS_BRANCH}$'\n\n'"This release has been auto-generated by Travis CI build #${TRAVIS_BUILD_NUMBER}." -t "${TRAVIS_BRANCH}" -a "main.pdf" "${TAG}"
